<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.1.5</VersionPrefix>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>
</Project>
